project:
  type: website
  output-dir: docs

website:
  title: "Isabelle Li - Portfolio"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - text: "Projects" 
        menu:
          - href: Projects/
            text: "All Projects"
          - href: Projects/Fire Alarm Prediction/Fire-Alarm-Prediction.qmd
            text: "Fire Alarm Prediction"
          - href: Projects/Philadelphia Housing Model/Philadelphia-Housing-Model.qmd
            text: "Philadelphia Housing Model"
            
      - text: "Research"
        menu:
          - href: Research/
            text: "All Research"
          - href: https://uxiaoo22.github.io/python/part1.html
            text: "Elephant Habitat Suitability"
            
      - text: "Writing"
        menu:
          - href: Writing/
            text: "All writing"
             
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
